#!/bin/bash
#################################################################################
#                                                                               # 
#  Pwm is the core to php with me. It contains all the necessary functions to   #
#  create you php web application.                                              #
#                                                                               # 
#  Author: Mushaheed Kapadia                                                    #
#                                                                               #
#################################################################################

# where the files are hosted
host="phpwithme.mushaheedkapadia.com"

# user wants to create a new application
if [ $1 == 'new' ]
then
	# make the app folder
	mkdir $2
	
	# make the directories
	mkdir $2/config
	mkdir $2/controllers
	mkdir $2/libs
	mkdir $2/models
	mkdir $2/public
	mkdir $2/public/views
	mkdir $2/public/stylesheets
	mkdir $2/public/scripts
	echo "created the directories"

	# get the configuration file
	cd $2/config
	wget $host/config/config.php
	cd ../..
	
	# get the controller files
	cd $2/controllers
	cd ../..

	# get the libs files 
	cd $2/libs
	wget $host/libs/scrypt.php
	wget $host/libs/jquery-2.1.1.min.js
	cd ../..

	# get models files
	cd $2/models 
	cd ../..

	# get public files
	cd $2/public
	wget $host/public/index.php
	cd ../..
	
	# get views 
	cd $2/public/views
	wget $host/public/views/head.html
	cd ../../..
	
	# get stylesheets
	cd $2/public/stylesheets
	wget $host/public/stylesheets/reset.css
	wget $host/public/stylesheets/global.css
	cd ../../..

	# get scripts
	cd $2/public/scripts
	wget $host/public/scripts/global.js
	cd ../../..
	
	echo ""
	echo "Project Created Successfully!"
	echo "cd $2"
	echo "Thank you!"
	echo "" 

	exit
fi

# user wants to add something
if [ $1 == 'add' ] 
then 
	# add a database
	if [ $2 == 'db' ] 
	then
		# get the database information
		dbtype=$3
		name=$4
		host=$5
		port=$6
		user=$7
		pass=$8
	
		# configuration file 
		config="config/config.php" 
		
		# add the database information to the configuration file
		sed -i "s/\/\/mark/\$_CONFIG['type_$name']='$dbtype';\n\$_CONFIG['host_$name']='$name';\n\$_CONFIG['port_$name']='$port';\n\$_CONFIG['user_$name']='$user';\n\$_CONFIG['pass_$name']='$pass';\n\/\/mark\n/" $config
	
		# echo out success
		echo "database added successfully"
	
		# exit on completion
		exit
	fi
	
	# add a library
	if [ $2 == 'lib' ]
	then 
		# get the path to the library
		libpath=$3
	
		# get the path to our libraries 
		pathlib="libs/"

		# copy it into ours
		cp $libpath $pathlib

		# echo out sucess
		echo "library added successfully"

		# exit on completion
		exit 
	fi

fi

