#!/bin/bash
#$1 should the type of php file
#$2 should be the path to the file 
#$3 - $x should be the fields to add

#help menu
if [ $1 == '-h' ]
then 
	echo ""
	echo "Usage:"
	echo ""
	echo 'easybake/addfieldsto.sh <name of file> <field_1> <field_2> ... <field_n>'
	echo ""
	exit
fi

newpath="php_framework/models"
counter=1

#use sed to insert after the '//mark', but need to figure out how to loop this 
for var in $@
do
	if [ "$counter" -gt "1" ]  #counter should be greater than two
	then
		sed -i "s/\/\/mark/\t\$$var;\n\t\t\/\/mark\n/" $newpath/$1
	fi
	counter=$((counter+1))	
done

echo "Successfully added fields to $1"
